### ISSUE TITLE
crashes on load

### ISSUE THREAD

**Issue by Bowen2404** [4-Space/4-Space-1.7#35]
Crash Report:
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[08:00:27] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:00:27] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:00:27] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[08:00:27] [main/INFO] [FML]: Forge Mod Loader version 7.99.32.1517 for Minecraft 1.7.10 loading
[08:00:27] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Mac OS X:x86_64:10.11, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
[08:00:27] [main/FATAL] [FML]: There appear to be jars extracted into the mods directory. This is VERY BAD and will almost NEVER WORK WELL
[08:00:27] [main/FATAL] [FML]: You should place original jars only in the mods directory. NEVER extract them to the mods directory.
[08:00:27] [main/FATAL] [FML]: The directories below appear to be extracted jar files. Fix this before you continue.
[08:00:27] [main/FATAL] [FML]: Directory LuckyBlock_1-8_v6-0-1 contains [MANIFEST.MF]
[08:00:27] [main/INFO] [STDOUT]: [cpw.mods.fml.relauncher.CoreModManager:discoverCoreMods:281]: #@!@# FML has crashed the game deliberately. Crash report saved to: #@!@# /Users/Bowen/Library/Application Support/minecraft/crash-reports/fml-crash-2015-10-30_08:00:27.txt
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.RuntimeException: Extracted mod jars found, loading will NOT continue
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:273)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:00:27] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/Bowen/Library/Application Support/minecraft for Forge Mod Loader
java.lang.RuntimeException: Extracted mod jars found, loading will NOT continue
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:273) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[08:00:27] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: Extracted mod jars found, loading will NOT continue
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:273) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Exception in thread "main" [08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Runtime.exit(Runtime.java:107)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.System.exit(System.java:968)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[08:00:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I am not good at reading crash reports so this may be a simple issue

**Comment by TheDWPCer** [comment]
btw way the problem was LuckyBlocks you used a 1.8 version not 1.7.10
